version: "3.9"
services:
  rol-api:
    image: api-bank
    container_name: bank_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql

  mysql:
    image: 9b6f08c39533
    container_name: db_bank
    environment:
      MYSQL_ROOT_PASSWORD: roberth456
      MYSQL_DATABASE: DB_Banco
      MYSQL_USER: hack4you
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  spring-network:

volumes:
  mysql-volume: