version: "3.9"
services:
  rol-api:
    image: Api-Bank
    container_name: Bank-Service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql
    environment:
      - JWT_SECRET=123456

  mysql:
    image: mysql:8
    container_name: DB_BANK
    environment:
      MYSQL_ROOT_PASSWORD: roberth456
      MYSQL_DATABASE: DB_Banco
      MYSQL_USER: hack4you
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  spring-network:

volumes:
  mysql-volume: